backend:
  name: git-gateway
  branch: main

media_folder: "src/assets"
public_folder: "../../assets"

collections:
  - name: "blog"
    label: "Artikel Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Artikel", name: "title", widget: "string" }
      - { label: "Tanggal Terbit", name: "pubDate", widget: "datetime" }
      - { label: "Deskripsi / Ringkasan", name: "description", widget: "text" }
      - { label: "Isi Konten", name: "body", widget: "markdown" }